# CircleCI 2.0 configuration file
# for ENCODE RNA-SEQ-PIPELINE
# Maintainer: Otto Jolanki

# Defaults and functions
defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:xenial-scm
  working_directory: ~/rna-seq-pipeline

machine_defaults: &machine_defaults
  machine:
    image: circleci/classic:201708-
  working_directory: ~/rna-seq-pipeline

make_tag: &make_tag
  name: make docker image tag
  command: |
    echo "export TAG=quay.io/encode-dcc/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" > ${BASH_ENV}

get_star_index: &get_star_index
  name: get star index for test
  command: |
    curl https://storage.googleapis.com/star-rsem-runs/reference-genomes/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz -o test_data/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz

# Jobs
version: 2
jobs:
  unittests:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/rna-seq-pipeline
    steps:
      - checkout
      - run:
          command: |
            cd src
            python -m unittest discover

  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *make_tag
      - run:
          name: build image
          command: |
            source ${BASH_ENV}
            docker login -u=${QUAY_ROBOT_USER} -p=${QUAY_ROBOT_USER_TOKEN} quay.io
            docker build --build-arg GIT_COMMIT_HASH=${CIRCLE_SHA1} --build-arg BRANCH=${CIRCLE_BRANCH} --build-arg BUILD_TAG=${TAG} -t $TAG .
            docker push $TAG
            docker logout

  test_PE_stranded:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *make_tag
      - run: *get_star_index
      - run: 
          command: |
            ls test_data
            echo $TAG

# Workflow
workflows:
  version: 2
  build_workflow:
    jobs:
      - unittests:
          filters:
            branches:
              only:
                - PIP-360_circleci
      - build:
          requires:
            - unittests
          filters:
            branches:
              only: 
                - PIP-360_circleci