# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - PIP-360_circleci
    machine:
      # specify the version you desire here
      image: circleci/classic:201708-01
    # declare environment variables 
    environment:
      TAG: quay.io/encode-dcc/rna-seq-pipeline:$CIRCLE_BRANCH_$CIRCLE_BUILD_NUM 

    working_directory: ~/rna-seq-pipeline

    steps:
      - checkout
      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "requirements.txt" }}
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            wget -N -c https://github.com/broadinstitute/cromwell/releases/download/34/cromwell-34.jar
      #- save_cache:
      #    paths:
      #      - ./venv
      #    key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: build image
          command: |
            echo "Hello Circle!"
            echo $TAG
            echo $CIRCLE_BRANCH
      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports